// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jejxuekmhohuagjplnhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Implanh1ZWttaG9odWFnanBsbmhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzcyMTEsImV4cCI6MjA2NjkxMzIxMX0.z1JtSEoDwy_RBSANPBQGnWHPPQNQzOgj6T_2LXo1FOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});